zenodo_data: <path of downloaded zenodo repository>

slurm:
  gpu_big: "<gpu partition name>"
  gpu_big_gres: "<gpu partion gres>"
  gpu_time_limit: "rule-dependent" # or a debugging time limit such as 00:15:00
